version: '3.8'
services:
  web:
    build:
      args:
        user: dockerUser
        uid: 1000
      context: .  # Diretório onde está o seu Dockerfile
    ports:
      - "8080:80"  # Mapeia a porta 80 do contêiner para a porta 8080 do host
    volumes:
      - ./:/var/www/html  # Mapeia o diretório do seu projeto para o diretório do Apache
    depends_on:
      - redis
    restart: always

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: userlaravel
      MYSQL_PASSWORD: laravel123      
      MYSQL_ROOT_PASSWORD: laravel123
    ports:
    - "3308:3306" # Porta do contêiner 3308 MySQL : Porta do host 3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql  # Adicione um volume para armazenar os dados do MySQL

  redis:
    image: redis:latest
    restart: always
